### ISSUE TITLE
Программа не находит единственную существующую в каталоге игру

### ISSUE THREAD

**Issue by KokarevaKatja** [alekseevm/javaqa-team-diplom-main#1]
# Описание
При проверке наличия единственной добавленной в каталог игры метод **containsGame()** возвращает false вместо true

# Локация дефекта
[Ссылка на код](https://github.com/alekseevm/javaqa-team-diplom-main/blob/fc5ab91dcc085ef6b00db08cdc59d95a21d0e907/src/main/java/ru/netology/GameStore.java#L32)

# Шаги воспроизведения
*** Запустить готовый [тест](https://github.com/alekseevm/javaqa-team-diplom-main/blob/fc5ab91dcc085ef6b00db08cdc59d95a21d0e907/src/test/java/ru/netology/GameStoreTest.java#L14)

ИЛИ
1. Открыть класс [GameStoreTest](https://github.com/alekseevm/javaqa-team-diplom-main/blob/fc5ab91dcc085ef6b00db08cdc59d95a21d0e907/src/test/java/ru/netology/GameStoreTest.java) в IDEA
1. Создать новый объект из класса **GameStore**
1. Создать новый объект игры и добавить его в каталог игр с помощью метода **publishGame()** c параметрами (“Roblox”, “arcade”)
1. Через вызов метода **asserTrue()** проверить, что метод **containsGame()** выполняет условие (true) и отображает единственную в каталоге игру

***Ожидаемый результат:*** метод **containsGame()** находит единственную существующую в каталоге игру и на ассерт  **asserTrue()** возвращает true
***Фактический результат:*** метод **containsGame()** не находит единственную существующую в каталоге игру и на ассерт  **asserTrue()** возвращает false

# Скриншот
![image 1](https://github.com/alekseevm/javaqa-team-diplom-main/blob/master/shouldContainOneGame.jpg)

# Окружение
•	Операционная система: Windows 11, x64, версия 21H2, сборка 22000.675
•	IDE: IntelliJ IDEA 2022.1.3 (Community Edition)
•	Java: Corretto-11 Amazon Corretto version 11.0.15

**Comment by alekseevm** [comment]
fixed
![изображение](https://user-images.githubusercontent.com/107930830/191722752-8dab7b37-6bad-4c42-9f1a-5de054175e1a.png)
