### ISSUE TITLE
Новое игровое время не суммируется с прошлым значением 

### ISSUE THREAD

**Issue by KokarevaKatja** [alekseevm/javaqa-team-diplom-main#4]
# Описание
При попытке добавить игроку новое игровое время через метод **addPlayTime()** при вызове метода **getMostPlayer()** возвращается изначальное количество времени без изменений. 

# Локация дефекта
[Ссылка на код](https://github.com/alekseevm/javaqa-team-diplom-main/blob/bf77eb22014eb5b6e1303ed1141226199495522a/src/main/java/ru/netology/GameStore.java#L46-L52)

# Шаги воспроизведения
Запустить готовый [тест](https://github.com/alekseevm/javaqa-team-diplom-main/blob/721dab69452cba85eab031b00d97b8994d15c451/src/test/java/ru/netology/GameStoreTest.java#L135) 

ИЛИ

1. Открыть командный проект "Java для тестировщиков" по [ссылке](https://github.com/alekseevm/javaqa-team-diplom-main.git) 	
1. Открыть класс **GameStoreTest** в IDEA
1. Создать игроков “Simon” и “Irina” и добавить им с помощью метода **addPlayedTime()** игровое время (“Simon” – 9, затем отдельно добавить новое время – 18; “Irina” – 26)  
1. Через вызов метода **asserEquals()** проверить, что метод возвращает игрока с наибольшим количеством игрового времени (actual получить через вызов метода **getMostPlayer()**

***Ожидаемый результат:*** метод **addPlayedTime()** суммирует прошлое и новое игровое время игрока “Simon”, а метод **getMostPlayer()** возвращает игрока “Simon” как обладателя наибольшего количество игрового времени

***Фактический результат:*** программа возвращает игрока “Irina” как обладателя наибольшего количество игрового времени

# Скриншот
![image 4](https://github.com/alekseevm/javaqa-team-diplom-main/blob/master/shouldAddNewPlayedTimeToOldOne.jpg)

# Окружение
•	Операционная система: Windows 11, x64, версия 21H2, сборка 22000.675
•	IDE: IntelliJ IDEA 2022.1.3 (Community Edition)
•	Java: Corretto-11 Amazon Corretto version 11.0.15

**Comment by alekseevm** [comment]
fixed
![изображение](https://user-images.githubusercontent.com/107930830/191724608-895e594f-34d2-453a-8eb1-328c1aac5f08.png)
