### ISSUE TITLE
При вызове метода суммирования игрового времени всех игроков возвращает ноль 

### ISSUE THREAD

**Issue by KokarevaKatja** [alekseevm/javaqa-team-diplom-main#5]
# Описание
Метод суммирования проигранного времени всех игроков **getSumPlayedTime()** при различных тестовых сценариях возвращает нулевое значение. Логика данного метода отсутствует в коде программы. 

# Локация дефекта
[Ссылка на код](https://github.com/alekseevm/javaqa-team-diplom-main/blob/8dd3c80d60c725b67f59baedb2ab7efd378e6f50/src/main/java/ru/netology/GameStore.java#L75-L78)

# Шаги воспроизведения
Запустить готовый [тест](https://github.com/alekseevm/javaqa-team-diplom-main/blob/8dd3c80d60c725b67f59baedb2ab7efd378e6f50/src/test/java/ru/netology/GameStoreTest.java#L159) 

ИЛИ

1. Открыть командный проект "Java для тестировщиков" по [ссылке](https://github.com/alekseevm/javaqa-team-diplom-main.git) 	
1. Открыть класс **GameStoreTest** в IDEA
1. Создать игроков “Petya”, “Irina”, “Simon”, “Liza” и добавить им с помощью метода **addPlayedTime()** игровое время 34, 0, 0, 0 соответственно
1. Через вызов метода **asserEquals()** проверить, что метод возвращает суммированное значение игрового времени всех игроков (actual получить через вызов метода **getSumPlayedTime()**)

***Ожидаемый результат:*** метод **getSumPlayedTime()** возвращает сумму игрового времени всех игроков равную 34

***Фактический результат:*** метод **getSumPlayedTime()** возвращает сумму игрового времени всех игроков равную 0

# Скриншот
![image 5](https://github.com/alekseevm/javaqa-team-diplom-main/blob/master/shouldGetSumPlayedTime.jpg)

# Окружение
•	Операционная система: Windows 11, x64, версия 21H2, сборка 22000.675
•	IDE: IntelliJ IDEA 2022.1.3 (Community Edition)
•	Java: Corretto-11 Amazon Corretto version 11.0.15

**Comment by alekseevm** [comment]
fixed

p.s. У тебя в описании местами перепутаны ОР и ФР

![изображение](https://user-images.githubusercontent.com/107930830/191723681-b397062f-c046-4030-b93e-e2c016f49735.png)

**Comment by KokarevaKatja** [comment]
Спасибо, исправила!
