### ISSUE TITLE
Метод summGenre не суммирует время проигранное во все игры конкретного жанра игроком

### ISSUE THREAD

**Issue by alekseevm** [alekseevm/javaqa-team-diplom-main#6]
# Описание
Метод summGenre не суммирует время проигранное во все игры конкретного жанра игроком, ответ всегда ноль.

# Локация дефекта
https://github.com/alekseevm/javaqa-team-diplom-main/blob/cdd3d7ef08a5fdfba64f49fc8b0fc0c83f1feb42/src/main/java/ru/netology/Player.java#L45-L57

# Шаги воспроизведения

1. Открыть код программы в IDEA
2. Перейти в класс PlayerTest
3. Запустить тест shouldSumGenreIfOneGame
4. Посмотреть результат

***Ожидаемый результат:*** - программа суммирует время проигранное игроком в игры одного жанра
***Фактический результат:*** - ответ всегда 0.

# Скриншот
![image 2](https://i.ibb.co/Mh5sgCw/image.png)

# Окружение

• Операционная система: Win10 x64
• IDE: IntelliJ IDEA 2022.1.3 (Community Edition)
• Java: Corretto-11 Amazon Corretto version 11.0.15

**Comment by KokarevaKatja** [comment]
Исправлены ошибки в методах sumGenre (условный оператор else не нужен) и play (не добавлялось проигранное игроком ранее количество часов)
![Скриншот 22-09-2022 112003](https://user-images.githubusercontent.com/108740955/191698265-a1ba8d7b-ac6a-4cb6-80c2-5d322b75f32d.jpg)
![Скриншот 22-09-2022 111713](https://user-images.githubusercontent.com/108740955/191698273-d9eff2a8-5446-4cde-906b-7da42f9eedf8.jpg)
