### ISSUE TITLE
Метод mostPlayerByGenre не возвращает игру жанра в который играли больше всего

### ISSUE THREAD

**Issue by alekseevm** [alekseevm/javaqa-team-diplom-main#7]
# Описание
Метод mostPlayerByGenre не возвращает игру жанра в который играли больше всего. 

# Локация дефекта
https://github.com/alekseevm/javaqa-team-diplom-main/blob/cdd3d7ef08a5fdfba64f49fc8b0fc0c83f1feb42/src/main/java/ru/netology/Player.java#L59-L63

# Шаги воспроизведения

1. Открыть код программы в IDEA
2. Перейти в класс PlayerTest
3. Запустить тест shouldMostPlayerByGenre
4. Посмотреть результат

***Ожидаемый результат:*** - метод возвращает игру из жанра, в которую играли больше всего
***Фактический результат:*** - null

# Скриншот
![image 2](https://i.ibb.co/3m35TgY/image.png)

# Окружение

• Операционная система: Win10 x64
• IDE: IntelliJ IDEA 2022.1.3 (Community Edition)
• Java: Corretto-11 Amazon Corretto version 11.0.15

**Comment by KokarevaKatja** [comment]
Исправлен дефект в методе mostPlayerByGenre (отстутсвовало тело кода метода)
![Скриншот 22-09-2022 113507](https://user-images.githubusercontent.com/108740955/191699301-a6b0389f-df56-45d4-9e37-cf8e70ab7555.jpg)
