### ISSUE TITLE
Метод Play не выкидывает RunTimeException.

### ISSUE THREAD

**Issue by alekseevm** [alekseevm/javaqa-team-diplom-main#8]
# Описание
Метод Play не выкидывает RunTimeException.

# Локация дефекта
https://github.com/alekseevm/javaqa-team-diplom-main/blob/cdd3d7ef08a5fdfba64f49fc8b0fc0c83f1feb42/src/main/java/ru/netology/Player.java#L28-L43

# Шаги воспроизведения

1. Открыть код программы в IDEA
2. Перейти в класс PlayerTest
3. Запустить тест shouldPlayRuntimeException
4. Посмотреть результат

***Ожидаемый результат:*** - программа выдаст комментарий с класса RunTimeException
***Фактический результат:*** - AssertionFailedError: Expected java.lang.RuntimeException to be thrown, but nothing was thrown. - Метод не реализован

# Скриншот
![image 2](https://i.ibb.co/GTqtFyj/image.png)

# Окружение

• Операционная система: Win10 x64
• IDE: IntelliJ IDEA 2022.1.3 (Community Edition)
• Java: Corretto-11 Amazon Corretto version 11.0.15

**Comment by KokarevaKatja** [comment]
Исправлена ошибка в методе play (условие о том, что если игра не была установлена, то метод должен выкидывать RuntimeException, не отражено в коде. При использовании неустановленной игры в тестах исключение не выбрасывалось).
![Скриншот 22-09-2022 114059](https://user-images.githubusercontent.com/108740955/191700604-02b1cbb3-43fc-45b9-8527-a3eabc7702fc.jpg)
